---
- name:  Launch Pool
  hosts: localhost
  connection: local
  roles:
    - role: avinetworks.avisdk

  vars:
    controller_ip: 10.52.1.100
    username: admin
    password: Avi12345!
    api_version: 18.1.3

- name: User Creation
  avi_user:
    controller: '{{ controller_ip }}'
    username: '{{ username }}'
    password: '{{ password }}'
    api_version: '{{ api_version }}'
    obj_username: "testuser1"
    obj_password: "avi12345"
    email: "test@msn.com"
    access:
      - role_ref: "/api/role?name-Tenant-Admin"
        tenant_ref: "/api/tenant/admin#admin"
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    is_supervisor: true
    default_tenant_ref: "/api/tenant?name=admin"
...
